import { NextResponse } from 'next/server';

export const maxDuration = 60; 


export async function POST(request) {
  try {
    const formData = await request.formData();
    const userPhoto = formData.get('userPhoto');
    const outfitPhoto = formData.get('outfitPhoto');

    // Pulling your specific variable name from Vercel
    const API_KEY = process.env.VITE_GEMINI_API_KEY;

    if (!API_KEY) {
      return NextResponse.json({ success: false, error: "API Key missing in Vercel." }, { status: 500 });
    }

    // 1. Convert the image files into pure Base64 strings (Google API requirement)
    const userBuffer = await userPhoto.arrayBuffer();
    const outfitBuffer = await outfitPhoto.arrayBuffer();
    
    const userBase64 = Buffer.from(userBuffer).toString('base64');
    const outfitBase64 = Buffer.from(outfitBuffer).toString('base64');

    /* =========================================================
       STEP 1: The Vision Prompt (Gemini 2.5 Flash)
       ========================================================= */
    const visionResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{
          parts: [
            { text: "Analyze Image 1 (the person) and Image 2 (the garment). Write a highly detailed, 1-paragraph image generation prompt describing this exact person wearing this exact garment. Accurately describe the person's facial features, hair, and body type. Then describe the garment's texture, color, and how it fits on them." },
            { inline_data: { mime_type: userPhoto.type, data: userBase64 } },
            { inline_data: { mime_type: outfitPhoto.type, data: outfitBase64 } }
          ]
        }]
      })
    });

    const visionData = await visionResponse.json();
    
    if (!visionResponse.ok) {
        throw new Error(visionData.error?.message || "Failed the vision analysis step");
    }

    // Extract the descriptive text generated by the AI
    const generatedPrompt = visionData.candidates[0].content.parts[0].text;
    console.log("Generated Prompt for Imagen:", generatedPrompt); // Visible in Vercel Logs

    /* =========================================================
       STEP 2: The Image Generation (Imagen 3)
       ========================================================= */
    const imageResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=${API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        instances: [
          { prompt: generatedPrompt }
        ],
        parameters: {
          sampleCount: 1
        }
      })
    });

    const imageData = await imageResponse.json();

    if (!imageResponse.ok) {
        throw new Error(imageData.error?.message || "Failed the image generation step");
    }

    // Imagen returns the new image as a raw base64 string
    const resultBase64Bytes = imageData.predictions[0].bytesBase64Encoded;
    const finalImageUrl = `data:image/jpeg;base64,${resultBase64Bytes}`;

    // Send the generated image back to the frontend to display!
    return NextResponse.json({ 
      success: true, 
      resultUrl: finalImageUrl 
    });

  } catch (error) {
    console.error("Gemini MVP Error:", error);
    return NextResponse.json({ success: false, error: error.message || "Server error" }, { status: 500 });
  }
}
